/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _AptRoute } from '../pages/apt';
import { Route as _IndexRoute } from '../pages/';
import { Route as _SearchRoute } from '../pages/search';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/apt': (typeof _AptRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/search': (typeof _SearchRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/apt': (typeof _AptRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/search': (typeof _SearchRoute)['_outputType'];
  }
}
