/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _AptRoute } from '../pages/apt';
import { Route as _ContentArticleRoute } from '../pages/content-article';
import { Route as _ContentRoute } from '../pages/content';
import { Route as _IndexRoute } from '../pages/';
import { Route as _IntroRoute } from '../pages/intro';
import { Route as _RecentTradesRoute } from '../pages/recent-trades';
import { Route as _SearchRoute } from '../pages/search';
import { Route as _TradesRoute } from '../pages/trades';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/apt': (typeof _AptRoute)['_inputType'];
    '/content-article': (typeof _ContentArticleRoute)['_inputType'];
    '/content': (typeof _ContentRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
    '/intro': (typeof _IntroRoute)['_inputType'];
    '/recent-trades': (typeof _RecentTradesRoute)['_inputType'];
    '/search': (typeof _SearchRoute)['_inputType'];
    '/trades': (typeof _TradesRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/apt': (typeof _AptRoute)['_outputType'];
    '/content-article': (typeof _ContentArticleRoute)['_outputType'];
    '/content': (typeof _ContentRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
    '/intro': (typeof _IntroRoute)['_outputType'];
    '/recent-trades': (typeof _RecentTradesRoute)['_outputType'];
    '/search': (typeof _SearchRoute)['_outputType'];
    '/trades': (typeof _TradesRoute)['_outputType'];
  }
}
